### ISSUE TITLE
Issues running the package

### ISSUE THREAD

**Issue by dmongia** [cran/highMLR#1]
> library(highMLR)
Warning message:
package ‘highMLR’ was built under R version 4.1.3 
> data(hnscc)
> mlhighCox(cols=c(6:15),
+           idSurv="OS",
+           idEvent="Death",
+           per=20,
+           fold = 3,
+           data=hnscc)
**Error: Element with key 'surv.coxph' not found in DictionaryLearner!**
>

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by dmongia** [comment]
Got it. 
Thanks
